require('dotenv').config();
const path = require('path');
const {
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_TIME,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_TIME,
  SQUADHELP_BANK_NUMBER,
  SQUADHELP_BANK_NAME,
  SQUADHELP_BANK_EXPIRY,
  SQUADHELP_BANK_CVC,
} = process.env;

module.exports = {
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_TIME,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_TIME,
  SALT_ROUNDS: 5,
  SQUADHELP_BANK_NUMBER,
  SQUADHELP_BANK_NAME,
  SQUADHELP_BANK_CVC,
  SQUADHELP_BANK_EXPIRY,
  CUSTOMER: 'customer',
  CREATOR: 'creator',
  MODERATOR: 'moderator',
  USER_ROLES: ['customer', 'creator', 'moderator'],
  CREATOR_ENTRIES: 'creator_entries',
  CONTEST_STATUS_ACTIVE: 'active',
  CONTEST_STATUS_FINISHED: 'finished',
  CONTEST_STATUS_PENDING: 'pending',
  CONTESTS_DEFAULT_DIR: 'public/contestFiles/',
  NAME_CONTEST: 'name',
  LOGO_CONTEST: 'logo',
  TAGLINE_CONTEST: 'tagline',
  OFFER_STATUS_MODERATOR_PENDING: 'moderator_pending',
  OFFER_STATUS_MODERATOR_REJECTED: 'moderator_rejected',
  OFFER_STATUS_PENDING: 'pending',
  OFFER_STATUS_REJECTED: 'rejected',
  OFFER_STATUS_WON: 'won',
  FILES_PATH: path.resolve(__dirname, '../..', 'public'),
  SOCKET_CONNECTION: 'connection',
  SOCKET_SUBSCRIBE: 'subscribe',
  SOCKET_UNSUBSCRIBE: 'unsubscribe',
  NOTIFICATION_ENTRY_CREATED: 'onEntryCreated',
  NOTIFICATION_CHANGE_MARK: 'changeMark',
  NOTIFICATION_CHANGE_OFFER_STATUS: 'changeOfferStatus',
  NEW_MESSAGE: 'newMessage',
  CHANGE_BLOCK_STATUS: 'CHANGE_BLOCK_STATUS',
  BANK_MIN_BALANCE: 0,
  //CHAT_CONTROLLER: 'chatController',
  CHAT_CONTROLLER: 'pgChatController',
  LOG_FILES_PATH: path.resolve(__dirname, './', 'log'),
  LOG_FILE_NAME: 'log.txt',
  LOG_BACKUP_CRON_SCHEDULE: '59 59 23 * * *',
  LOG_BACKUP_FILES_PATH: path.resolve(__dirname, './', 'log/backup'),
  EMAIL_SMTP_AUTH_SETTINGS: {
    host: 'smtp.ukr.net',
    auth: {
      user: process.env.EMAIL_SMTP_USER,
      pass: process.env.EMAIL_SMTP_PASS,
    },
    secure: true,
    port: 2525,
  },
};
